xnmt/decoder.py, xnmt/encoder.py, xnmt/search_strategy.py, xnmt/translator.py, xnmt/xnmt_train.py
Separated the embedder out of the encoder, which simplifies encoder code
=> Separated embedder and encoder

README.md, xnmt/batcher.py, xnmt/decoder.py, xnmt/input.py, xnmt/length_normalization.py, xnmt/loss_tracker.py, xnmt/model_params.py, xnmt/search_strategy.py, xnmt/sentence_stats.py, xnmt/translator.py, xnmt/xnmt_decode.py, xnmt/xnmt_evaluate.py, xnmt/xnmt_run_experiments.py, xnmt/xnmt_train.py
In different parts of the code base, variable names were written differently. This commit makes things more consistent, and also adds a note to the README about common abbreviations.
=> Made variable names more consistent

examples/debug.yaml, examples/speech.yaml, examples/standard.yaml, xnmt/options.py, xnmt/xnmt_run_experiments.py
Makes location of log files configurable, and also makes it possible to specify defaults that use a special symbol `<EXP>` that will be replaced by the experiment name.
=> Template experiment names

xnmt/evaluator.py, xnmt/input.py, xnmt/xnmt_decode.py, xnmt/xnmt_evaluate.py, xnmt/xnmt_train.py
These may be helpful for debugging / preventing crashes
=> max_src_len for decoding, max_num_training_sents

xnmt/loss_tracker.py, xnmt/xnmt_train.py
behavior is now that train PPLs are reported every 1k sents, and only dev reporting (incl. model saving and LR decay) is configurable via "eval_every"
=> decoupled reporting of train / dev loss

examples/debug.yaml, examples/modular.yaml, xnmt/decoder.py, xnmt/encoder.py, xnmt/xnmt_train.py
Added dropout in encoder / decoder RNNs.
=> Full dropout support

examples/speech.yaml, xnmt/options.py
also, fix small issue in speech config
=> allow running empty experiments (relying only on default experiment)

xnmt/length_normalization.py, xnmt/search_strategy.py, xnmt/xnmt_decode.py
Some variants of length normalization may be applied already during the beam search rather than after the search, which may produce better results.
=> Partial length norm

xnmt/decoder.py, xnmt/serializer.py, xnmt/xnmt_train.py
mostly resolving issues with loading pretrained models
=> Refactor and fix decoder init

examples/random-search.yaml, examples/random-search2.yaml, xnmt/options.py, xnmt/xnmt_run_experiments.py
Feature that performs random search over model / search parameters, by simply specifying the choices in the config file. Search can be sequential or in parallel, depending on how experiment runner is started.
=> Random search

examples/preproc.yaml, xnmt/preproc.py, xnmt/xnmt_preproc.py, xnmt/xnmt_run_experiments.py
This commit makes it possible to perform some rudimentary preprocessing directly within xnmt. There are still several missing components, which will be added in following commits:
1) Tokenization/detokenization
2) Separate specification of what preprocessing should be done before evaluation
=> Add preprocessing capability

examples/standard.yaml, xnmt/xnmt_train.py
This addresses the previous comment that it would be nice to filter at training time.
=> Generalized training time filtering

xnmt/evaluator.py, xnmt/input.py, xnmt/serializer.py, xnmt/vocab.py, xnmt/xnmt_decode.py, xnmt/xnmt_evaluate.py, xnmt/xnmt_run_experiments.py, xnmt/xnmt_train.py
I think these are several porting problem from the previous xnmt code. For the future, I think it is better for the developers to refer to this cheat sheet: http://python-future.org/compatible_idioms.html
=> Ported python2 codes to python3

examples/debug.yaml, examples/modular.yaml, examples/random-search.yaml, examples/random-search2.yaml, xnmt/decoder.py, xnmt/embedder.py, xnmt/encoder.py, xnmt/model_params.py, xnmt/options.py, xnmt/serializer.py, xnmt/train_test_interface.py, xnmt/translator.py, xnmt/xnmt_train.py
Addresses mostly:
- modular encoder
- random search
- improved error messages
- code cleanup
=> Various improvements

examples/debug.yaml, xnmt/attender.py, xnmt/decoder.py, xnmt/embedder.py, xnmt/encoder.py, xnmt/input.py, xnmt/model_globals.py, xnmt/model_params.py, xnmt/serializer.py, xnmt/vocab.py, xnmt/xnmt_decode.py, xnmt/xnmt_train.py
this fixes some serialization problems + hopefully restores most of the functionality that was broken
=> Various improvements pt 2

examples/standard.yaml, xnmt/evaluator.py, xnmt/loss_tracker.py, xnmt/output.py, xnmt/translator.py, xnmt/xnmt_decode.py, xnmt/xnmt_run_experiments.py, xnmt/xnmt_train.py
- optionally restart Adam when applying LR decay
- revert to best checkpoint when applying LR decay
- specify num attempts before LR decay
- determine early stopping / LR decay based on BLEU and other criteria
- eval test data only at end of experiment
=> Optimization / learning schedule

xnmt/input.py, xnmt/xnmt_train.py
Useful to train on large (especially non-text) data without having to load everything into memory, as well as to bring more randomness into the training.
=> Sample from data @ each epoch

xnmt/attender.py, xnmt/decoder.py, xnmt/embedder.py, xnmt/encoder.py, xnmt/model_globals.py, xnmt/model_params.py, xnmt/serialize_container.py, xnmt/serializer.py, xnmt/xnmt_decode.py, xnmt/xnmt_run_experiments.py, xnmt/xnmt_train.py
Save recent n best models, so we can later easily add checkpoint averaging / ensembling.
Also addresses #117: dynet model -> `dynet_param_collection`, model_params -> `serialize_container`, the term model refers to the top of the hierarchy (e.g. translator or retriever).
=> Recent checkpoints & better naming

examples/debug.yaml, xnmt/batcher.py, xnmt/decoder.py, xnmt/embedder.py, xnmt/expression_sequence.py, xnmt/loss_tracker.py, xnmt/translator.py, xnmt/xnmt_train.py
This commit simplified batcher. I also noticed that there was probably a bug where a minority of sentences (particularly when using very small data) were becoming unaligned, and this behavior was inconsistent. I'm not sure why this was happening in the previous code, but I think this commit should fix it.
=> Simplified batcher and fixed bug

script/code/clean.sh, xnmt/conv_encoder.py, xnmt/decoder.py, xnmt/embedder.py, xnmt/encoder.py, xnmt/evaluator.py, xnmt/expression_sequence.py, xnmt/input.py, xnmt/length_normalization.py, xnmt/loss_tracker.py, xnmt/model_globals.py, xnmt/options.py, xnmt/output.py, xnmt/preproc.py, xnmt/pyramidal.py, xnmt/retriever.py, xnmt/search_strategy.py, xnmt/serialize_container.py, xnmt/serializer.py, xnmt/training_corpus.py, xnmt/translator.py, xnmt/vocab.py, xnmt/xnmt_decode.py, xnmt/xnmt_run_experiments.py, xnmt/xnmt_train.py
As you can see, I am removing extra whitespaces from the XNMT source code. I think github can detect it. I also added a bash script to remove the whitespace from the code under the script/code/clean.sh for easy future use.
My editor can detect the extra spaces, so it is a bit bothering to see red everywhere. I think it is a good practice also.
=> Removed extra whitespaces from xnmt

xnmt/expression_sequence.py, xnmt/input.py
Currently, I am adding the ability to transpose in the reader. Apparently, the dataset from the speech has the format that is transposed from what the reader assumed.
=> Cont Vector Reader should be able to read vector shape that is not assumed by the reader.

xnmt/reports.py
This commit will make it possible to generate reports for each of the translations. The first element of the report will be a visualization of the attention weights.
This is a work in progress, as it isn't yet integrated with the pipeline.
=> [WIP] Adding reporting functionality and visualization of attention weights

xnmt/action.py, xnmt/attender.py, xnmt/batcher.py, xnmt/embedder.py, xnmt/input.py, xnmt/length_normalization.py, xnmt/loss_tracker.py, xnmt/options.py, xnmt/output.py, xnmt/preproc.py, xnmt/pyramidal.py, xnmt/residual.py, xnmt/search_strategy.py, xnmt/sentence_stats.py, xnmt/tee.py, xnmt/xnmt_train.py
I hope the handling of the learning rate is correct according to the new DyNet conventions?
=> fixed learning rate, moved to new-style classes

xnmt/encoder.py
Create a more general encoder class called linear_encoder to replace the too specific HarwathImageEncoder, which is essentially a linear projection.
=> add linear_encoder

examples/speech_retrieval.yaml, xnmt/embedder.py, xnmt/specialized_encoders.py
I tested it with 
python xnmt/xnmt_run_experiments.py examples/speech_retrieval.yaml
things seem to be right.
=> this is the Tilburg's encoder

xnmt/encoder.py
Change 'else: if:' to 'elif:', modify the class description, delete some commented codes
=> improve fully connected layer\

.gitignore, setup.py, test/analyze_log.py, test/xnmt_test.py, xnmt/__init__.py, xnmt/encoder.py, xnmt/specialized_encoders.py, xnmt/xnmt_run_experiments.py, xnmt/xnmt_train.py
You can do:
```python3 setup.py develop```
To install python "live" package directory that changes over time.
To establish the PATH, we just need to ```import xnmt``` before importing any modules from xnmt. (This should be done in executables)
=> Better packaging

examples/debug.yaml, xnmt/embedder.py, xnmt/model_globals.py, xnmt/xnmt_train.py
I added weight noise as a global option because I'm planning on adding it to LSTMs as well.
=> Weight noise in embeddings

xnmt/xnmt_run_experiments.py
I'm not sure what the purpose of this import was, but it's throwing me an error and doesn't seem to be used anywhere.
=> remove unused package import

examples/debug.yaml, xnmt/decoder.py, xnmt/decorators.py, xnmt/embedder.py, xnmt/encoder.py, xnmt/model.py, xnmt/retriever.py, xnmt/segment_transducer.py, xnmt/segmenting_encoder.py, xnmt/translator.py
=> word dropout

.gitignore, requirements.txt, script/code/reload_example.py, test/__init__.py, test/test_run.py, test/test_training.py, xnmt/search_strategy.py, xnmt/segmenting_encoder.py, xnmt/tee.py
- Fixed a few python2/3 compatibility problems
- Replaced enum with enum34, which hopefully should fix the Travis problem.
- I've observed that `test_translator_loss` and `test_overfitting` occasionally fail, so I've set the seed to 0 to make them reproducible. It may be worth investigating, but it's not very useful to have it make CI tests fail randomly.
=> [WIP] Fixed some test problems

setup.py
First attempt to fix https://github.com/neulab/xnmt/issues/199 which may break linux compile
=> Fix cython compile on mac

xnmt/expression_sequence.py
Spotted by @DevSinghSachan in #184 but I thought we should fix this right away.
=> Fix expression sequence len

xnmt/embedder.py
According to this paper: https://arxiv.org/abs/1710.01329
=> Added ability to fix embedding norm

examples/standard.yaml, xnmt/xnmt_run_experiments.py
This will help avoid forgetting which configuration was used for a particular experiment. Also, slightly modified the standard setting to make it a little bit stronger.
=> Made an option to save the config file

test/config/translator_loss.yaml, xnmt/decoder.py, xnmt/translator.py, xnmt/xnmt_train.py
Currently, the Regressor is trained at sentence level as the process is very slow otherwise.
=> [WIP] Adding Baseline to Reinforce

xnmt/training_strategy.py
This change stabilizes Reinforce without Baseline.
Reinforce with Baseline is yet to be stabilized.
=> Debugging Reinforce

xnmt/xnmt_run_experiments.py
Fixes https://github.com/neulab/xnmt/issues/214
=> Remove writing of yaml file by default

test/config/forced.yaml, test/test_run.py, xnmt/xnmt_decode.py
You can now run an experiment with forced decoding, see `forced.yaml` for an example.
=> Exposed forced decoding to xnmt_decode

test/test_beam_search.py, test/test_decoding.py, test/test_embedder.py, xnmt/output.py, xnmt/translator.py, xnmt/xnmt_decode.py
Decoding can return the scores of the hypotheses.
=> Made scores returnable

test/config/forced.yaml, xnmt/generator.py, xnmt/output.py, xnmt/xnmt_decode.py
This makes it possible to simultaneously perform forced decoding and loss calculation, then compare the two values. This should help debug problems in decoding or masking during training.
=> Debugging for decoding

xnmt/loss_tracker.py
=> Put more decimals on loss reporting

examples/component_sharing.yaml, examples/modular.yaml, examples/preproc.yaml, examples/pretrained.yaml, examples/report.yaml, examples/speech.yaml, examples/standard.yaml, requirements.txt, test/config/component_sharing.yaml, test/config/encoders.yaml, test/config/forced.yaml, test/config/load_model.yaml, test/config/random_search_test_params.yaml, test/config/random_search_train_params.yaml, test/config/reload.yaml, test/config/reload_exception.yaml, test/config/report.yaml, test/config/segmenting.yaml, test/config/standard.yaml, test/config/translator_loss.yaml, test/config/translator_report.yaml, test/test_beam_search.py, test/test_decoding.py, test/test_encoder.py, test/test_training.py, xnmt/attender.py
Adds dot product attention. Note this changes "StandardAttender" to "MlpAttender"
=> Dot attention

examples/standard.yaml, xnmt/decoder.py
Hi Graham,
I have created this new branch in order to add the label smoothing code as there were a few merge conflicts in the older branch.
=> Added Label Smoothing

examples/component_sharing.yaml, examples/preproc.yaml, examples/pretrained.yaml, examples/report.yaml, examples/retrieval.yaml, examples/speech.yaml, examples/speech_retrieval.yaml, examples/standard.yaml, test/config/component_sharing.yaml, test/config/encoders.yaml, test/config/forced.yaml, test/config/load_model.yaml, test/config/prior-segmenting.yaml, test/config/random_search_test_params.yaml, test/config/random_search_train_params.yaml, test/config/reload.yaml, test/config/reload_exception.yaml, test/config/report.yaml, test/config/retrieval.yaml, test/config/segmenting.yaml, test/config/standard.yaml, test/config/translator_loss.yaml, test/config/translator_report.yaml, xnmt/train.py, xnmt/xnmt_decode.py, xnmt/xnmt_run_experiments.py
This addresses #240. It's mostly a quick hack and not very pretty, but we can further refactor things later.
=> made xnmt_decode serializable

xnmt/evaluator.py, xnmt/xnmt_evaluate.py
Implemented GLEU score evaluation.
Test: The scores were compared with those of nltk implementation for ~5000 pairs of sentences at sentence and corpus level.
And its integration with xnmt was tested.
=> Gleu Score

xnmt/xnmt_evaluate.py
added bracketing to print for python3 support in external evaluation script implementation
=> added bracketing to print for python3 support

examples/transformer.yaml, test/config/transformer.yaml, test/test_run.py, xnmt/embedder.py, xnmt/initializer.py, xnmt/linear.py, xnmt/optimizer.py, xnmt/training_regimen.py, xnmt/transformer.py, xnmt/translator.py
Created a new branch to resolve merge conflicts.
=> TF_New  (updated pull requests from https://github.com/neulab/xnmt/pull/246)

.travis.yml, doc/source/programming_style.rst
This ceases Python 2 support per. Fixes https://github.com/neulab/xnmt/issues/242
=> Remove requirement for supporting Python 2.

doc/requirements.txt, doc/source/api_doc.rst, doc/source/doc_util.py, readthedocs.yml
This fixes the RTD configuration issues introduced by #294. The API doc is still not compiling properly because of import issues, which I think was already broken prior to #294.
=> Partial fix to docs

.gitignore, xnmt/inference.py
Fixes https://github.com/neulab/xnmt/issues/292
=> Create parent directories of inference files

examples/05_preproc.yaml, xnmt/preproc.py
(+ small fix in preproc example config)
=> Preproc: new normalizer that removes punctuation

xnmt/serialize/serializer.py, xnmt/serialize/tree_tools.py
=> catch case of Ref within shared parameters

xnmt/training_regimen.py, xnmt/training_task.py
- remove ```load_data()```, handle data loading in ```advance_epoch()``` instead
- fix data reloading between epochs when ```sample_train_sents``` is given
=> fix data reloading

xnmt/persistence.py
=> fix case of exp_dir==WD

xnmt/embedder.py
=> Makes word embedding more efficient

docs/conf.py, docs/experiment_config_files.rst
Same as #341 but without merge conflicts
=> Fix pathing for readthedocs

docs/api_doc.rst, docs/experiment_config_files.rst, recipes/las-tedlium/config.las-pyramidal.yaml, recipes/stanford-iwslt/config.en-vi.yaml, xnmt/decoder.py, xnmt/evaluator.py, xnmt/exp_global.py, xnmt/input_reader.py, xnmt/persistence.py, xnmt/settings.py, xnmt/tee.py, xnmt/xnmt_run_experiments.py
This addresses a few things mentioned in #343 and #336:
- fixed recipe configs
- improvements to documentation
- make sure GIT revision is written to log files
=> Improvements to recipes, logging, and documentation

docs/api_doc.rst, docs/preprocessing.rst, requirements.txt, xnmt/preproc.py
=> Use sentencepiece python API

docs/preprocessing.rst, requirements-extra.txt, requirements.txt, xnmt/preproc.py
I've been having trouble installing sentencepiece via pip. I didn't try very hard to solve it, but others might have the same problem so I suggest making it an optional dependency.
=> Sentencepiece as optional dependency

docs/api_doc.rst, docs/experiment_config_files.rst, docs/getting_started.rst, docs/preprocessing.rst, docs/programming_style.rst, docs/translator_structure.rst, docs/writing_xnmt_classes.rst, xnmt/exp_global.py, xnmt/preproc.py
Adds cross links and improves/fixes description in several places.
=> Doc improvements

recipes/kftt/README.md, recipes/kftt/config.kftt.en-ja.yaml, recipes/kftt/download.sh
Adds a recipe for KFTT en-ja. Gets BLEU score 23.14 after 12 epochs
=> Add a recipe for KFTT

docs/conf.py, xnmt/eval_task.py, xnmt/length_normalization.py, xnmt/persistence.py, xnmt/util.py, xnmt/xnmt_evaluate.py
Activates the sphinx_autodoc_typehints plugin and fixes some typing issues that had previously caused the plugin to crash.
=> fix sphinx_autodoc_typehints

script/code/conv_checkpoints_to_model.py, test/test_serializer.py, xnmt/attender.py, xnmt/decoder.py, xnmt/embedder.py, xnmt/eval_task.py, xnmt/evaluator.py, xnmt/inference.py, xnmt/input_reader.py, xnmt/linear.py, xnmt/loss.py, xnmt/mlp.py, xnmt/output.py, xnmt/param_collection.py, xnmt/persistence.py, xnmt/plot.py, xnmt/preproc.py, xnmt/preproc_runner.py, xnmt/retriever.py, xnmt/search_strategy.py, xnmt/training_task.py, xnmt/transducer.py, xnmt/transformer.py, xnmt/translator.py, xnmt/vocab.py, xnmt/xnmt_evaluate.py
Fixes/improves a few issues found via PyCharm code inspection. A couple were actual bugs, and most were coding style related and might prevent subtle bugs in the future.
=> Code cleanup

xnmt/__init__.py, xnmt/evaluator.py, xnmt/preproc.py, xnmt/residual.py, xnmt/segmenting_composer.py
=> assert + fix yaml_tag for all Serializable classes

test/test_run.py, xnmt/embedder.py
Fixes [#398](https://github.com/neulab/xnmt/issues/398).
=> Fix broken pretrained embeddings option

xnmt/length_normalization.py, xnmt/search_strategy.py
This enhances ```BeamSearch``` to support adding a value to the log prob of ```</s>``` for more explicit length control.
=> Boost </s>

docs/index.rst, docs/save_file_format.rst, examples/01_standard.yaml, script/code/avg_checkpoints.py
Adds a script to perform checkpoint averaging, along with some documentation on file formats used for model saving.
=> Checkpoint averaging

requirements-extra.txt, requirements.txt
script/code/conv_checkpoints_to_model.py uses docopt, so I added it to the requirements.
=> add docopt to requirements.txt

docs/api_doc.rst, test/test_training.py, xnmt/eval_task.py, xnmt/evaluator.py, xnmt/exp_global.py, xnmt/loss.py, xnmt/loss_calculator.py, xnmt/loss_tracker.py, xnmt/model_base.py, xnmt/segmenting_encoder.py, xnmt/training_regimen.py, xnmt/training_task.py, xnmt/translator.py
Choices are ```sum``` and ```avg```.
It took me some time to understand the semantics of the loss builder, so I tried documenting and renaming things to make it easier to understand. Maybe @philip30 could let me know in case I misunderstood anything.
=> Configure how to combine batched losses

xnmt/batcher.py, xnmt/inference.py
This is a PR to fix https://github.com/neulab/xnmt/issues/423
The first commit is simply to ensure that tests fail until this error is fixed.
=> Fix forced decoding error

xnmt/eval_task.py, xnmt/input.py, xnmt/training_regimen.py, xnmt/util.py
This will help at least give some hints where things are crashing. We can probably make the logging more extensive later by having each Input print info about its representation (which sentence number is it, etc.)
=> Printing of debugging on crashes

xnmt/input_reader.py
* Print a message when the file starts loading
* Count lines more efficiently
* Cache line counts so they don't need to be re-counted every epoch
=> A few changes to support input of large files

xnmt/training_task.py
Tiny bug fix for dev combinator (maybe due to new version of asteval?). I'll just merge.
=> Bug fix for dev_combinator

xnmt/input_reader.py
Just add one line to convert sentence piece encoded bytes into string
=> fix sentence piece input reader byte string

examples/14_report.yaml, test/config/report.yaml, test/config/segmenting.yaml, test/config/speech.yaml, xnmt/exp_global.py, xnmt/inference.py, xnmt/plot.py, xnmt/reports.py, xnmt/retriever.py, xnmt/segmenting_encoder.py, xnmt/settings.py, xnmt/translator.py
This attempts to make reporting more reusable by introducing dedicated reporter classes. Currently, only an HTML attention reporter is implemented, but others could be added more easily now. I've commented out some of the related code from the segmentation models because I'm not sure how they work and to what extent they need to be maintained? In any case, it should be easy to re-add this functionality if needed.
=> Improve reporting

script/code/rehash_model.py
Fixes https://github.com/neulab/xnmt/issues/461 with a new script based on @mbollmann 's script that re-hashes an arbitrary model to new random hashes.
=> Added script to re-hash model components for ensembling

xnmt/__init__.py, xnmt/tee.py, xnmt/xnmt_run_experiments.py
=> log unhandled exceptions to file

xnmt/input_readers.py, xnmt/sent.py
Fixes https://github.com/neulab/xnmt/issues/498
=> Return newly called constructor instead of deepcopy

test/config/classifier.yaml, xnmt/eval/metrics.py, xnmt/models/classifiers.py, xnmt/xnmt_evaluate.py
Fixes a bug in the ```SequenceClassifier``` related to batched decoding, and adds F-Score evaluation
=> fix classifier and add f-score evaluator

xnmt/input_readers.py, xnmt/loss_calculators.py, xnmt/losses.py, xnmt/output.py, xnmt/sent.py
This is the fix for #511 
Additionally, I added weighting capabilities to the CompositeLoss in loss calculator and simplify the code in sent.py so that future modification of the base SimpleSentence will less likely to break the SegmentedSentence.
=> Fix output

xnmt/eval/tasks.py, xnmt/inferences.py, xnmt/sent.py, xnmt/settings.py, xnmt/train/regimens.py, xnmt/utils.py
My attempt to print it only to file but not stdout was not successful because the DyNet function uses print instead of returning a string, so I changed it to print the CG only with debug settings (solves part of #495).
=> print CG on error only in debug mode

test/config/seg_report.yaml, xnmt/specialized_encoders/segmenting_encoder/segmenting_encoder.py
This is just a hotfix of segmentation report breaking when doing reporting on dev sets.
=> Fixed report breaking

xnmt/eval/tasks.py, xnmt/modelparts/attenders.py, xnmt/modelparts/embedders.py, xnmt/models/base.py, xnmt/models/language_models.py, xnmt/models/sequence_labelers.py
Some work toward #439 and #438 (at places that hopefully don't cause merge conflicts with other PRs). These are cosmetic changes so I'll merge when tests are passing.
=> improved imports & type annotations

xnmt/eval/tasks.py, xnmt/experiments.py, xnmt/length_norm.py, xnmt/loss_calculators.py, xnmt/models/translators.py, xnmt/preproc.py, xnmt/reports.py, xnmt/search_strategies.py, xnmt/sentence_stats.py, xnmt/settings.py, xnmt/tee.py, xnmt/utils.py, xnmt/vocabs.py, xnmt/xnmt_decode.py, xnmt/xnmt_evaluate.py, xnmt/xnmt_run_experiments.py
Progress toward #438 and #439. Only cosmetic changes, won't need a review.
=> Import and types

xnmt/modelparts/decoders.py, xnmt/models/classifiers.py, xnmt/models/translators.py
Fix to issue [554](https://github.com/neulab/xnmt/issues/554)
=> Refactored interaction between models and DecoderStates
