xnmt/xnmt_decode.py
xnmt/xnmt_run_experiments.py
xnmt/xnmt_train.py

A couple of common dynet flags  (`--dynet-mem` and `--dynet-gpu-ids`) can be necessary for running xnmt.
As of now, both flags cause argparse to throw an error in both xnmt_train and xnmt_decode. `--dynet-gpu-ids` also causes argparse to crash in xnmt_run_experiment.
This commit adds the flags as optional arguments so they can be passed transparently to dynet.

add optional arguments to pass to dynet

---

examples/debug.yaml
examples/modular.yaml
examples/speech.yaml
xnmt/conv_encoder.py
xnmt/encoder.py
xnmt/options.py
xnmt/serializer.py
xnmt/xnmt_decode.py
xnmt/xnmt_evaluate.py
xnmt/xnmt_run_experiments.py
xnmt/xnmt_train.py

This is to allow parametrizing encoders arbitrarily from the config files.
We can certainly do more refactoring, but it's ready to use so I thought I'd throw it out now.
One question is whether and how to document encoder parameters. There's 3 parameters that every encoder has: type, input_dim, output_dim. The encoder-specific parameters are kind of formalized in BuilderEncoder.use_params(), we could think about developing this more fully and even creating documentation automatically. I need to take care of other things now, but I'll be making heavy use of this and probably be pushing fixes/updates.

Encoder spec via dictionaries

---

examples/debug.yaml
examples/modular.yaml
xnmt/encoder.py
xnmt/residual.py
xnmt/xnmt_train.py

Code is a bit cleaner now. A last remaining refactoring step might be to collapse related encoders that have the same parameters into one encoder class.

refactored encoder module

---

xnmt/evaluator.py
xnmt/input.py
xnmt/xnmt_train.py

map in python2 returns list where in python3 returns generator. I think the best practice is to use the six.moves.map() which returns a generator and put it into the list() constructor if we expect it to produce list.

Solved porting problem

---

xnmt/embedder.py
xnmt/encoder.py
xnmt/expression_sequence.py

Currently, when using contvec inputs and RNN encoders, the contvec would produce a tensor expression sequence, and the RNN would use pick() for each input. LazyNumpyExpressionSequence helps avoid those unnecessary operations.

lazy expression sequence to avoid unnecessary pick() operations

---

xnmt/tee.py

(got broken by the recent python3 fix)

fixed python2 when writing non-unicode logs

---

xnmt/evaluator.py
xnmt/serializer.py
xnmt/tee.py

Haven't checked in python2, but I am pretty sure it works.
Btw, we actually need to always use six.moves.map that returns generator as list(map()) expression is 2 times N operations in python2.

Fixes some python2-3 compatibilities

---

examples/debug-report.yaml
xnmt/reports.py
xnmt/translator.py
xnmt/xnmt_decode.py

This commit makes it possible to create HTML reports for each translated sentence, including attention visualization by @shrutijpalaskar . This is not written in a super-extensible way at the moment, but I plan on stress-testing the extensibility by trying to use this for speech-to-text translation, or visualizing layers of the network, etc. This will be added in a future pull request.

Added ability to create reports for translations

---

xnmt/serializer.py

six.u() only works for string/unicode inputs

deserialization fix for python 2.7

---

xnmt/batcher.py
xnmt/xnmt_train.py

When choice of mini-batches plays a particularly large role in the stability of the training, it might be good to ensure different mini-batches on each epoch. This commit makes this possible by ensuring that the batches are re-created every epoch when using a batcher that includes randomness.

Made packer re-pack batches at every epoch when shuffling

---

examples/retrieval.yaml
xnmt/retriever.py
xnmt/training_corpus.py
xnmt/xnmt_decode.py
xnmt/xnmt_train.py

In retrieval tasks, it's common to only measure retrieval accuracy over the elements in the test database. This commit makes it possible to measure accuracy in this way.

Make it possible to measure recall on only a subsample of the database IDs

---

xnmt/xnmt_decode.py

Quick matter I picked up while trying to grok the option system:
The example configs are broken right now by missing `candidate_id_file`, an option that seems to be intended to be optional, but is required. 
Specifically, due to [the option parsing at this line](https://github.com/neulab/xnmt/blob/master/xnmt/options.py#L27), an option is required if the `required` flag is set to `True` or if the `required` flag is set to `None`, and the default value is `None`. 
I did not want to accidentally break functionality by changing the default value of `candidate_id_file`, so I made it optional.

make argument explicitly optional because default is None

---

examples/speech.yaml
xnmt/expression_sequence.py
xnmt/input.py

Currently `ContVecReader` assumes indexing by `array[word_id,feat_id]` by default, and all downstream processing (padding, etc.) assumes this order. However, while this order makes sense for numpy (which is row major), it's different from DyNet's canonical ordering (which is column major). This causes things to be confusing conceptually, and causes problems when you use continuous vectors through `as_tensor()` e.g. convolutional encoders wouldn't work out-of-the-box.
The PR makes the handling of ordering for input and downstream processing to be `array[feat_id,word_id]`. Most downstream code will not change, as everything is handled in the input classes, but for models inputting arrays in the old format to `ContVecReader`, this means that the `transpose: True` option will have to be added …

Made ContVecReader dimensions be consistent with DyNet ordering

---

xnmt/encoder.py
xnmt/specialized_encoders.py

This is a refactoring of the RHN encoder to make it more concise. Here are some changes:
1. Instead of relying on external classes, simply adds parameters to the RHN encoder class. Hopefully this makes things a little simpler.
2. Instead of using ExpressionSequences, uses regular DyNet expressions (within the encoder).
3. Fixes a bug (?) where T was using a tanh instead of a sigmoid.
This seems to have fixed the numerical stability issues.

Refactoring of RHN Encoder

---

xnmt/decoder.py
xnmt/search_strategy.py

Fixing Beam Search to be compatible with the current Decoder.
The following discrepancy was observed by @msperber when using Beam Search for inferencing using a trained model:
```
beam	BLEU	
1	0.294	
2	0.269	
3	0.269	
4	0.265
```	
Test:
Testing on the above model now provides consistency in inference scores. And following BLEU scores were observed:
```
beam	BLEU4	
1	0.2652	
2	0.2751	
3	0.2794
```
Tested on the unit-test suite

Resolving inconsistencies in Beam Search

---

test/test_batcher.py
test/test_beam_search.py
test/test_decoding.py
test/test_training.py
xnmt/attender.py
xnmt/batcher.py
xnmt/embedder.py
xnmt/expression_sequence.py
xnmt/lstm.py
xnmt/retriever.py
xnmt/translator.py
xnmt/xnmt_train.py

This is to make it easier for batch masks to be passed on between the different modules:
- there is a new Mask class, including code to apply that mask to dynet expressions to reduce code duplication
- masks are now stored and passed on as attributes of Batch or ExpressionSequence objects, and never explicitly
- to make ExpressionSequences immutable per convention, so we don't have to worry about side effects, masks no longer modify the expression inside an ExpressionSequence, but create a new ExpressionSequence instead

Refactor mask

---

xnmt/cython/src/functions.h
xnmt/translator.py

For some reason, next() doesn't seem to work as expected. I am unable to reason why and if it is just for me.
**Earlier:**
Predicted Sentence (before using next()) :     
`  they have each dealer , i don &apos;t know what else they start doing because , i see , there are , lots of people that for example , my mom is already , uh , she took to five calls </s> </s> </s> </s> </s> </s> </s>   `
Reference Sentence (before using next()) :        
`have every person . therefore , i don &apos;t know what they are going to do . because , already , already are a to much people that , by example , my mother <unk> have reach the twenty five calls </s> </s> </s> </s> </s>  ` 
Predicted Sentence (after using next()):     
`      they   `
Reference Sentence (after using next()):      
`     have   `
` …

Minor Tweaks in TranslatorReinforceLoss

---

xnmt/decoder.py
xnmt/search_strategy.py
xnmt/translator.py

This is a second attempt at https://github.com/neulab/xnmt/pull/194
This commit makes the decoder stateless, removing any of its global variables and instead holding them in a separate state object. This will probably reduce potential for bugs in search algorithms, etc.
Also, input feeding is put on by default. It also makes a change to input feeding, feeding in the context, not the hidden layer of the MLP. It might be worth feeding in the hidden layer of the MLP instead, but I don't think this is the standard way of doing things (as noted by @cindyxinyiwang )

Made the decoder stateless again

---

.gitignore
test/config/standard.yaml
test/test_run.py
xnmt/serializer.py

Currently it seems that activating length normalization will cause crashing on the second epoch when evaluating on the dev set. This adds a unit test to demonstrate the breakage with the following error:
Start training in minibatch mode...   
Epoch 1.0000: train_loss/word=3.066 (words=140, words/sec=5200.58, time=0-00:00:00)   
initialized PolynomialNormalization({'apply_during_search': True, 'm': 1})   
> Checkpoint   
Epoch 1.0000 dev [auxiliary] BLEU4: 0   
Epoch 1.0000 dev Loss: 2.994 (words=140, words/sec=4514.20, time=0-00:00:00)   
Epoch 1.0000: best dev score, writing model to examples/output/standard.mod   
Epoch 2.0000: train_loss/word=2.994 (words=140, words/sec=1628.74, time=0-00:00:00)   
Traceback (most recent call last):
File "xnmt/xnmt_run_experiments.py", line 166, in …

[WIP] Fix length normalization when evaluating on dev set

---

xnmt/decoder.py

For input feeding, we should add the dimension of the context, not the dimension of the lstm

fix decoder input feeding dimension

---

examples/standard.yaml
xnmt/batcher.py

- Fix a crash in word batcher when words_per_batch was smaller than the largest sentence length
- Alternatively to words_per_batch, configure word batcher via avg_batch_size, which might be more intuitive to use

Fix word batcher & configure via avg_batch_size

---

xnmt/decoder.py
xnmt/loss_tracker.py
xnmt/xnmt_train.py

This fixes a bug that was counting padding symbols in the denominator when calculating PPL. Now the word count matches the actual number of words included in the file (as measured by `wc`).
Note, this change won't affect your BLEU scores, but it has the potential to have a *large effect* on your perplexity/loss scores. Please be aware of it if you're reporting perplexity scores in your experiments, or comparing with other toolkits.

Fixed a bug counting padding symbols for PPL

---

xnmt/loss_tracker.py

The first words/sec reported in each epoch appears to be a bit smaller than others. The timer is not set correctly.

Fixed tiny words/sec reporting bug

---

xnmt/training_regimen.py
xnmt/training_task.py
xnmt/xnmt_evaluate.py

This implements ```initial_patience``` that allows delaying the first LR decay further than subsequent LR decays which are controlled by ```patience``` (previously ```attempts_before_lr_decay```).
This is useful when using a ```schedule_metric``` other than ```loss```, which often suffers from the optimization metric's high variance during the early training stages.

Initial patience

---

test/config/multi_task.yaml
xnmt/training_regimen.py
xnmt/training_task.py

- implemented ```SerialMultiTaskTrainingRegimen``` which trains task 1 to convergence, then task 2, etc. (useful for pretraining/finetuning)
- fixed some things I broke when refactoring yesterday
- improved naming (let me know if you have other naming suggestions):
- ```SimpleTrainingRegimen``` (unchanged)
- ```SameBatchMultiTaskTrainingRegimen``` (previously ```JointMultiTaskTrainingRegimen```)
- ```AlternatingBatchMultiTaskTrainingRegimen``` (previously ```SerialMultiTaskTrainingRegimen```)
- ```SerialMultiTaskTrainingRegimen``` (new)

implement SerialMultiTaskTrainingRegimen + fixes

---

xnmt/preproc.py

- sentencepiece models weren't being built for me on a clean install because the `preproc` folder wasn't being made before sentencepiece was initialized. 
- This error was being hidden because stderr messages were only being written given an unrelated condition.
This PR fixes those bugs for Python 3.6. Python 2 should work but no promises.

make sentpiece model dir; fix stderr preproc output

---

xnmt/attender.py

The _general_ attender of https://arxiv.org/abs/1508.04025 is a nice compromise between the more complicated MlpAttender and the unparametrized DotAttender. It is implemented here.
Summary of below -- GeneralLinear seems to be at least on par, BLEU-wise, with the MLP. May be better, but I have my doubts. The improvement may be due to its having fewer parameters, since the train set is so small. It's also considerably slower, which is unintuitive to me, but maybe someone can rewrite line 131 
- train words/sec=2574.60ish
- Dev bleu 0.016222765483504837 (20 epochs)
- Test bleu 0.02349701978746616 (20 epochs)
- train words/sec=1540.73ish
- Dev bleu 0.031945032510106094 (20 epochs)
- Test bleu 0.04681154243162295 (20 epochs)

add general linear attender of https://arxiv.org/abs/1508.04025

---

test/config/speech.yaml
xnmt/serialize/serializer.py
xnmt/serialize/tree_tools.py
xnmt/translator.py

Previously, the reference resolution when saving a model went breadth-first, which caused the model to be specified inside the evaluators and then referenced elsewhere. This made it difficult to load/overwrite certain parts of the model because references are not followed when overwriting. This PR changes to a more natural resolution order, which is probably still not perfect in all situations, but better than before. In the future, we might try following references when doing load/overwrite, and/or keeping track of the reference hierarchy as specified in the original config file.
Also included is an unrelated quick fix for speech reporting.

Better ref resolution, fix speech reporting

---

xnmt/evaluator.py
xnmt/xnmt_evaluate.py

I did not see a way to evaluate simple sequence accuracy, i.e., the percentage of hypothesis sequences that exactly match the references.
This may not be too relevant for machine translation, but can be for other sequence-to-sequence tasks, and seems basic enough that it should exist.
If I missed something and this already exists, please let me know.

Add sequence accuracy as an evaluation metric

---

xnmt/training_task.py

Previously, the ```cur_attempt``` wasn't reset to 0 after decaying LR, so that effectively the patience was 1 directly after a decay. With this PR, the ```cur_attempt``` is set to 0 after a decay, which is probably the behavior people would expect.

fix patience

---

xnmt/attender.py
xnmt/batcher.py
xnmt/eval_task.py
xnmt/exp_global.py
xnmt/experiment.py
xnmt/param_init.py
xnmt/preproc_runner.py
xnmt/serialize/serializer.py
xnmt/training_regimen.py

This is a suggestion to perform basic type checking of values specified in YAML configs. This will catch some common errors such as ```overwrite: Fals``` being interpreted as equal to ```True``` (the spelling mistake makes this a string rather than bool).
It uses Python type annotations, so I moved some of the type documentation from the docstring to the method definition. Either is fine according to the Google documentation guidelines, although it might be a bit confusing for people not familiar with this, so let me know if you have reservations.
As a limitation, this currently only checks "normal" types (like ```bool``` or ```Experiment```), not things from the typing module (like ```List[int]``` or ```Optional[Experiment]```), which means it can currently only catch some of the simpler …

Basic config type checking

---

xnmt/eval_task.py
xnmt/evaluator.py
xnmt/inference.py
xnmt/preproc.py
xnmt/preproc_runner.py
xnmt/serialize/serializer.py
xnmt/tee.py
xnmt/util.py
xnmt/xnmt_evaluate.py

This is partly a code cleanup, partly making evaluation more flexible:
- xnmt_evaluate via command line mode now takes either a string like ```bleu,gleu```as metrics, or a fully configurable list of python object such as ```WEREvaluator(case_sensitive=True),BLEUEvaluator()]```. Previously, the latter was not possible, so evaluators could only be used with default settings. 
- the same holds for the metrics of the ```AccuracyEvalTask```.
I do think the ```bleu,gleu``` string shortcut is a good idea for the command line because we don't want to specify python objects if we don't have to, and the required extra code is quite simple. The main question is whether this is true for YAML configs also: do we want to support ```eval_metrics:wer,bleu``` or only ```eval_metrics: [!WEREvaluator {}, …
```

Refactor scoring

---

xnmt/length_normalization.py
xnmt/search_strategy.py

- fix length normalization not working in case of ```apply_during_search=False```
- speed up ```PolynomialNormalization``` by precomputing powers of sequence lengths that are otherwise recomputed a large number of times. Overall speedup of beam search is about 10%.

Length norm improvements

---

xnmt/loss_tracker.py
xnmt/training_task.py

Currently, checkpoints are made whenever an epoch is finished, or more often in case ```dev_every``` is set.  It is not possible to have checkpoints less often than at every epoch though, even if setting ```dev_every``` to a value greater than the number of training sentences. This commit changes this behavior: finishing an epoch has no special significance if ```dev_every``` is set, so that we can set it so that checkpoints are less often than once every epoch (useful e.g. in connection with ```sample_train_sents```).

dev_every: remove special handling of new epoch events

---

.gitignore
doc/source/getting_started.rst
requirements-extra.txt
requirements.txt

Fixes https://github.com/neulab/xnmt/issues/329
Looks like all tests and training pass without librosa and exact h5 version, so here is a cleanup. Also small addition to gitignore for the test directory.

Removed unnecessary requirements

---

xnmt/persistence.py

Tuples in the Serializable hierarchy are not supported because they are immutable. This catches tuples so that we can fail fast and avoid hard to debug follow up errors.

raise exception when tuple is found in the serializable hierarchy

---

docs/experiment_config_files.rst

I find it easier to navigate the examples from the documentation directly.
This PR adds an "example" subsection under the "Experiment configuration file format" of the docs where the example yaml and python files are included.
Also adds a bit of syntax highlighting to the yaml code samples.

Add examples to the documentation

---

docs/experiment_config_files.rst
docs/getting_started.rst
examples/03_multiple_exp.yaml
examples/04_settings.yaml
recipes/stanford-iwslt/README
setup.py
xnmt/xnmt_evaluate.py

This allows typing ```xnmt``` instead of ```python -m xnmt.xnmt_run_experiments```, and ```xnmt_evaluate``` instead of ```python -m xnmt.xnmt_evaluate``` after running setup.py.

xnmt shortcut

---

examples/01_standard.yaml
xnmt/mlp.py

Right now the choices are ``tanh``, ``relu``, ``sigmoid``, ``elu``, ``selu`` or ``asinh``. Defaults to ``tanh``

Choose the activation function for MLPs

---

xnmt/vocab.py

This adds an option to vocab to make it possible to read the vocabulary from the `.vocab` file generated by sentencepiece. This saves a lot of preprocessing.

Reuse sentencepiece vocab file

---

requirements.txt
test/config/dev_combinator.yaml
xnmt/evaluator.py
xnmt/training_regimen.py
xnmt/training_task.py

This PR introduces the ability to combine together multiple development scores to determine the final score that should be used to do learning rate decay, etc. It also improves the documentation about the default of using the first development task.
The reason why this is "[WIP]" is because using `eval()` is a security hole: https://stackoverflow.com/questions/661084/security-of-pythons-eval-on-untrusted-strings
It'd be nice to be able to come up with a safe version.
Fixes https://github.com/neulab/xnmt/issues/293

[WIP] Added ability to combine together dev scores

---

requirements.txt
xnmt/batcher.py

When using avg_batch_size, the corresponding number of words per batch was first computed by considering source words only, but then later when building the batches the sum of source + target words were counted. This is a fix to consistently use the sum of source + target words.
Also improves the batcher doc a little bit and fixes requirements as pointed out by @pierregodard .

Fix avg batch size

---

xnmt/eval_task.py
xnmt/training_regimen.py

Previously the training regimen was in control of calling ```set_train()``` to switch between training and eval steps, but that led to some inconsistency when the training regimen was skipped (e.g. when setting ```run_for_epochs=0```). This PR moves calls to ```set_train()``` closer to where they are actually needed in the code in the hope of avoiding some of these side effect issues.

Reorganize set_train()

---

.gitignore
docs/writing_xnmt_classes.rst
test/test_run.py
xnmt/__init__.py
xnmt/conv.py
xnmt/evaluator.py
xnmt/ff.py
xnmt/lstm.py
xnmt/param_collection.py
xnmt/persistence.py
xnmt/pyramidal.py
xnmt/search_strategy.py
xnmt/segmenting_composer.py
xnmt/specialized_encoders.py
xnmt/transducer.py

This fixes #373 by checking automatically that class name are unique, that the ```@serializable_init``` decorator is used, that my_params() is not called after ```__init__()``` was completed, and that ```dy.ParameterCollection``` is not passed as argument to serializable sub-components.
Fixes a good number of places where some of these things were not handled correctly. I don't believe any of those would have actually caused problems, but it's still good to have more consistency.

Automatic Bugchecks

---

examples/16_transformer.yaml

The Transformer example config file didn't have an inference object specified, so it was raising an exception during training.

Add inference to transformer config

---

xnmt/decoder.py

- Using a sparse tensor to directly generate lexicon matrix. It seems to be faster
- Account for unicode when opening lexicon

Speed up discrete lexicon creation

---

xnmt/preproc.py

For multiple min/ max values (min_0, ..) fixed the min assignment and the assignment in general.

SentenceFilterLength: fix min sentence length and max/min index

---

xnmt/training_task.py

The dev word count was previously taken from the last dev task, but the score from the frist task.
Now the word count is taken from the first task as well.

fix dev loss word count is taken from the first dev task

---

docs/api_doc.rst
examples/13_speech.yaml
test/test_evaluation.py
xnmt/eval_task.py
xnmt/evaluator.py
xnmt/inference.py
xnmt/levenshtein.py
xnmt/xnmt_evaluate.py

Refactors evaluators to support sentence-level evaluation. The main idea is to add a ```SentenceLevelEvaluator``` abstract class:
- subclass implement only ```eval_one_sent()``` to compute scores for a single sentence
- ```SentenceLevelEvaluator.evaluate()``` and ```SentenceLevelEvaluator.evaluate_multi_ref()``` take care of computing corpus-level scores. This uses the new ```SentenceLevelEvalScore.aggregate()``` method that must be implemented by the corresponding score classes.
Most classes (except the BLEU evaluators and ```ExternalEvaluator```) adhere to this new interface.
This comes with a few new features:
- ```SentenceLevelEvaluator``` subclasses support writing out of sentence-level scores to a YAML file.
- Multi-reference evaluation is now supported by most evaluators.
- WER/CER …

Sentence level evaluation

---

xnmt/preproc.py

Added a preprocessing filter that can filter sentences by regular expression.
Example usage:
```
- !PreprocFilter
in_files:
- examples/data/head.ja
- examples/data/head.en
out_files:
- examples/output/head.filter.ja
- examples/output/head.filter.en
specs:
- type: matching-regex
regex_trg: "you"
```

Preproc regex filter

---

recipes/las-tedlium/config.las-pyramidal.yaml
xnmt/inference.py
xnmt/search_strategy.py

A little while ago max-len was moved from ``SimpleInference`` to ``BeamSearch``, but the argument wasn't removed from ``SimpleInference``.

Fix max len

---

xnmt/training_regimen.py

If ```per_task_backward = True``` (default), backward is invoked individually for each task to accumulate gradients and then the CG is renewed. I.e. ```True``` helps save memory while ```False``` can bring speed-ups when used with auto batching. The previous behavior was identical to ```per_task_backward  = False```.

per_task_backward option for SameBatchMultiTaskTrainingRegimen

---

xnmt/tee.py

This fixes an error encountered when using XNMT in a Docker environment.

Fix encoding for logger file handlers

---

test/config/component_sharing.yaml
xnmt/__init__.py
xnmt/persistence.py

This fixes a problem that prevented reference-sharing of components that are list / dictionary items (e.g. sharing individual modules of the modular seq transducer).

Fix list item ref-sharing

---

docs/save_file_format.rst
examples/12_multi_task.yaml
xnmt/mlp.py
xnmt/optimizer.py
xnmt/training_regimen.py
xnmt/util.py

This replaces #413 and adds 3 features to the optimizers that can help stabilize training:
- ```update_every```: simulated large-batch training
- ```skip_noisy```: keep track of a moving average and a moving standard deviation of the log of the gradient norm values, and abort a step if the norm of the gradient exceeds four standard deviations of the moving average. Reference: https://arxiv.org/pdf/1804.09849.pdf
UPDATE: ```clip_norm``` is already the default DyNet behavior and is now removed from this PR.

Optimization features

---

xnmt/__init__.py
xnmt/fixed_size_att.py

This implements the basic fixed-size memory model according to Britz et. al 2017: ﻿Efficient Attention using a Fixed-Size Memory Representation; https://arxiv.org/abs/1707.00110
It's implemented as a sequence transducer and can, for example, be used by specifying a modular transducer with an LSTM module followed by this new module. I've tested it on a character translation task and got results in line with the paper.

Fixed size attention

---

examples/05_preproc.yaml
test/config/preproc.yaml
xnmt/preproc.py
xnmt/preproc_runner.py

Implements the reversible, language-independent tokenizer from the appendix of https://arxiv.org/pdf/1804.08205
While at it, I also made some places a bit more YAML-like. I did not change the filterers because their initializer arguments are a bit more complicated and might require **kwargs syntax which currently is not supported by the XNMT serializer (although it would be nice to have..).

Unicode tokenizer

---

xnmt/preproc.py

The Unicode tokenizer had a problem with splitting Unicode diacritics as punctuation:
> http://unicode.org/faq/char_combmark.html
These should not be segmented, so this PR fixes this.

Fix unicode tokenizer

---

test/test_training.py
xnmt/loss_tracker.py
xnmt/optimizer.py
xnmt/training_regimen.py

Previously, the same-batch regimen computed time/words jointly for all tasks. This PR computes and logs times individually if per_task_backward is activated.
In addition, includes a minor cleanup by removing the update_weights flag from the training regimens which was only used in one unit test, where the same effect is now achieved via a new DummyTrainer.

Better computation time tracking for same-batch multi tasking

---

test/config/lm.yaml
test/test_run.py
test/test_training.py
xnmt/__init__.py
xnmt/eval_task.py
xnmt/experiment.py
xnmt/input.py
xnmt/input_reader.py
xnmt/lm.py
xnmt/seq_labeler.py
xnmt/training_task.py

This introduces a language model that is a subclass of ```TrainableModel``` (not ```GeneratorModel```). It can be trained and used with the loss evaluator (but not the accuracy or decoding evaluators).
The code is straight forward, the main question to discuss is handling of source / target inputs. The XNMT training code is currently built around the assumption that we always have a source side and a target side. The language model requires only a source side. I can think of a few ways to handle this:
- Current solution: simply configuring the trg_file identical to the src_file, and then ignoring the trg sentences in the model. A bit hacky, but requires no changes to the training and evaluation code.
- Make a non-parallel version of ```SimpleTrainingTask``` that reads only source inputs …

Language Model

---

xnmt/experiment.py
xnmt/inference.py
xnmt/input_reader.py
xnmt/optimizer.py
xnmt/param_collection.py

This PR has a bunch of fixes for robustness when doing lots of experiments. Probably only one is debatable, commenting out the initial model saving when starting training (`experiment.py`). I actually wasn't sure why this was necessary in the first place, and it can significantly slow down the start of training (and by proxy, the speed of debugging implementation).

Several miscellaneous robustness fixes

---

test/test_persistence.py
xnmt/persistence.py

As mentioned in #467.
A test of a simple configuration with the following encoder seemed to work:
```
encoder: !ModularSeqTransducer
modules: !Repeat
times: 3
content: !BiLSTMSeqTransducer {}
```
@neubig could you take a look if this will work as expected for the multilayer transformer configs?

initial implementation of repeat syntax

---

examples/21_self_attention.yaml
xnmt/classifier.py
xnmt/transform.py

This makes the transformer encoder more compact by using the repeat syntax and adding an MLP Transform convenience class that performs 0 or more non-linear transforms, then a linear transform.

Added MLP convenience class

---

docs/experiment_config_files.rst
examples/01_standard.yaml
examples/02_minimal.yaml
examples/03a_multiple_exp.yaml
examples/03b_multiple_exp.yaml
examples/03c_multiple_exp.yaml
examples/04_settings.yaml
examples/05_preproc.yaml
examples/06_early_stopping.yaml
examples/09_programmatic.py
examples/13_speech.yaml
examples/14_report.yaml
examples/20_subword_sample.yaml
examples/21_self_attention.yaml
xnmt/experiments.py
xnmt/persistence.py
xnmt/xnmt_run_experiments.py

This is a proof-of-concept for #367 / #383:
- config files can now be single experiments, lists of experiments, or (as before) dictionaries of experiments. In the first 2 cases, experiments have to have a name argument, and the third case the name argument is taken from the dictionary key.
- this allows us to call ```xnmt /path/to/saved-model.mod``` which will resume the previous experiment.
- ```Experiment``` now has a simple state that checks whether everything is finished or not. If resuming a finished experiment, nothing will happen, otherwise the whole experiment is carried out.
- a ```--resume``` flag is added that makes sure that ```{EXP_DIR}```, ```{EXP}``` etc. is set to the value that was previously used, rather than to the values corresponding to the current context. This makes …

Named experiments and resume option

---

xnmt/batchers.py

The ```InOrderBatcher``` is mainly used for inference so 1 would be a reasonable default batch size which helps to simplify config files a bit.

default batch size 1 for InOrderBatcher

---

test/test_persistence.py
xnmt/persistence.py

Crashed under the following conditions:
- a model requires an argument which it does not keep as a member variable under the same name
- reference-sharing occurs one level down of this argument
Also included is a unit test to catch this.

Fix a bug when saving models

---

xnmt/eval/tasks.py
xnmt/models/base.py
xnmt/models/classifiers.py
xnmt/models/language_models.py
xnmt/models/sequence_labelers.py
xnmt/models/translators.py

Will fix #507.
Is ```get_primary_loss``` still needed? The only place it's currently used is here, not sure if that's on purpose or was forgotten: https://github.com/neulab/xnmt/blob/master/xnmt/eval/tasks.py#L89

fix models base interface

---

docs/experiment_config_files.rst
docs/index.rst
docs/visualization.rst
requirements-extra.txt
requirements-extra/README
requirements-extra/audio-feature-extraction.txt
requirements-extra/build-doc.txt
requirements-extra/ensembling-scripts.txt
requirements-extra/sentencepiece.txt
requirements-extra/tensorboard.txt
requirements.txt
xnmt/loss_trackers.py
xnmt/tee.py
xnmt/utils.py
xnmt/xnmt_run_experiments.py

This PR uses the tensorboardX package to write out training logs that can be read by tensorboard. We previously wrote out the same information via the structured logger and I've simply replaced using the structured logger here by using the tensorboardX writer. The structured logger still exists but is not used currently. Tensorboard outputs are organized as ```exp_name/train_task_name/[train|dev]/[loss_name]```
Tensorboard outputs are written without further configuration necessary The only thing that has to be done to visualize outputs is to install tensorflow, and run ```tensorboard --logdir [logdir]```.

Tensorboard integration

---

test/config/cascade.yaml
test/test_persistence.py
test/test_run.py
xnmt/models/base.py
xnmt/persistence.py
xnmt/reports.py
xnmt/thirdparty/charcut/charcut.py

In #508 I had attempted to fix an issue that required every ```__init__``` argument of a ```Serializable``` to be stored via ```self.arg_name = arg_name```. This is done anyways pretty much everywhere in XNMT, but would be nice to get rid of. The fix had introduced some new issues though which are probably worse and can lead to model saving or loading failing. I haven't been able to come up with a fix yet, so this PR reverts the previous fix and adds several unit tests and minor refactoring that will help with debugging and developing a fix. Also included is a test config with a cascading example (which was the one that led to some problems and made me aware of this).

Revert bugfix and add more unit tests

---

test/test_persistence.py
xnmt/persistence.py

The current design requires Serializable objects to manually save their init arguments as instance attributes. This PR is a first improvement on this and makes this happen automatically, fixing a few unit tests. It should still be made a bit safer though in a future PR.

Serializable instance attributes

---

xnmt/batchers.py
xnmt/eval/metrics.py
xnmt/experiments.py
xnmt/hyper_params.py
xnmt/inferences.py
xnmt/length_norm.py
xnmt/modelparts/embedders.py
xnmt/modelparts/scorers.py
xnmt/param_initializers.py
xnmt/persistence.py
xnmt/reports.py
xnmt/sent.py
xnmt/specialized_encoders/self_attentional_am.py
xnmt/train/regimens.py
xnmt/train/tasks.py
xnmt/transducers/pyramidal.py

Using ```hyperparam.Scalar``` etc. in my config file led to a failing type check because ```Scalar``` is not a ```float```.
To solve this, I made ```Scalar``` an instance of Python's abstract base class ```numbers.Real```, and updated the type annotations to use numbers.Real instead of float. Also includes some general improvements toward more consistent type annotations.
I think as a general goal we should try to use the abstract base class type variants whenever possible (e.g. also for ```numbers.Integral```, and possibly for a new string-type ABC) because that will enable making hyperparams and ```!Ref``` to be compatible with these types.
Update: I also slightly updated ```DefinedSequence``` to use its first list item as initial value.

Hyperparams as numbers.Real

---

xnmt/inferences.py
xnmt/models/classifiers.py

Fixes https://github.com/neulab/xnmt/issues/530
Note that this results in two alternative code paths for decoding: one for "batch" where the entire file is read in, batched, and processed, and one for "stream" where a single example is decoded at a time. Currently I set "stream" to default, as batch decoding isn't implemented in a way that makes it any more efficient (see https://github.com/neulab/xnmt/issues/526).

Created stream decoding

---

examples/21_self_attention.yaml
xnmt/transducers/positional.py
xnmt/transducers/residual.py
xnmt/transducers/self_attention.py

This adds missing dropout operations in 3 places in the self-attention/transformer architecture of example 21, namely after positional encodings, residual connections, and attention matrix (see AIAYN paper). I've confirmed that this improves results when setting these to a conservative value (e.g. 0.1).

Transformer dropout

---

xnmt/rl/policy_gradient.py
xnmt/specialized_encoders/segmenting_encoder/segmenting_encoder.py

This is a very minor change to correct the policy gradient when calculating z_normalization. I think Rewards should be normalized not only per sequence but also per item in the minibatch. So, the number of items in a minibatch will really impact the learning behaviour of the policy gradient.

Fix Z_Normalization

---

xnmt/search_strategies.py

This patch fixes Beam Search's stopping criteria. If searching e.g. with a beam size of five, beam search should return the five best-scoring hypotheses. Previously beam search was returning the five *shortest* hypotheses. Thankfully with modest beam sizes, the end of sentence marker is not usually in the beam until it's at least somewhat appropriate, so the effect is shockingly small.
The new termination strategy is to wait until the score of the best active hypothesis is lower than the Nth best complete hypothesis (where N=beam size). Assuming each subsequent word has a negative score, this criteria guarantees that no active hypothesis could ever be better than the N complete hypotheses already found.
To verify the effectiveness of this patch I've done some experiments with a …

fix to beam search stopping criteria
